'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation';
import Header from '../components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}){
  const path = usePathname().split('/')
  
  return (
    <html lang="en">
      <head>
        <title>C&L Correa Optics</title>
      </head>
      <body className={inter.className}>
        <div className='flex flex-col w-[100vw] h-[100vh]'>
          { (path.includes('appointments') || path.includes('clients') ||
            path.includes('products') || path[1] === '')  && 
            (!path.includes('admin') && !path.includes('login')) ?
          <Header/> : null}
          {children}
        </div>
      </body>
    </html>
  )
}
