import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}){
  return (
    <html lang="en">
      <head>
        <title>C&L Correa Optics</title>
      </head>
      <body className={inter.className}>
        <div className='flex flex-col w-[100vw] h-[100vh]'>
          <Header/>
          {children}
        </div>
      </body>
    </html>
  )
}
